/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-04-09 02:22:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<body data-open=\"click\" data-menu=\"vertical-menu\" data-col=\"2-columns\"\r\n");
      out.write("\tclass=\"vertical-layout vertical-menu 2-columns  fixed-navbar\">\r\n");
      out.write("\t<div class=\"app-content content container-fluid\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"content-header row\">\r\n");
      out.write("\t\t\t\t<div class=\"content-header-left col-md-6 col-xs-12 mb-1\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"content-header-title\">Chartjs Line Chart</h2>\r\n");
      out.write("\t\t\t\t\t\t<!-- <button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary btn-min-width mr-1 mb-1\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"getChart()\">primary</button>-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"breadcrumb-wrapper col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\">Chartjs</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"breadcrumb-item active\">Line Chart</li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"logging\">logging start</a>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content-body\">\r\n");
      out.write("\t\t\t\t<!-- line chart section start -->\r\n");
      out.write("\t\t\t\t<section id=\"chartjs-line-charts\">\r\n");
      out.write("\t\t\t\t\t<!-- Line Chart -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"card-title\">Simple Line Chart</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"heading-elements-toggle\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon-ellipsis font-medium-3\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"heading-elements\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-inline mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"collapse\"><i class=\"icon-minus4\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"reload\"><i class=\"icon-reload\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"expand\"><i class=\"icon-expand2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"close\"><i class=\"icon-cross2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body collapse in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"card-block chartjs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<canvas id=\"line-chart\" height=\"500\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<section id=\"chartjs-bar-charts\">\r\n");
      out.write("\t\t\t\t\t<!-- Bar Chart -->\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"card-title\">Bar Chart</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"heading-elements-toggle\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon-ellipsis font-medium-3\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"heading-elements\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-inline mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"collapse\"><i class=\"icon-minus4\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"reload\"><i class=\"icon-reload\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"expand\"><i class=\"icon-expand2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"close\"><i class=\"icon-cross2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body collapse in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<canvas id=\"bar-chart\" height=\"400\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<section id=\"chartjs-pie-charts\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Simple Pie Chart -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"card-title\">Simple Pie Chart</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"heading-elements-toggle\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon-ellipsis font-medium-3\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"heading-elements\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-inline mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"collapse\"><i class=\"icon-minus4\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"reload\"><i class=\"icon-reload\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"expand\"><i class=\"icon-expand2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"close\"><i class=\"icon-cross2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body collapse in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<canvas id=\"simple-pie-chart\" height=\"400\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Simple Doughnut Chart -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"card-title\">Simple Doughnut Chart</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"heading-elements-toggle\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon-ellipsis font-medium-3\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"heading-elements\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-inline mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"collapse\"><i class=\"icon-minus4\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"reload\"><i class=\"icon-reload\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"expand\"><i class=\"icon-expand2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"close\"><i class=\"icon-cross2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body collapse in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<canvas id=\"simple-doughnut-chart\" height=\"400\"></canvas>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- // line chart section end -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("</body>\r\n");
      out.write("<!-- BEGIN PAGE LEVEL JS-->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"./resources/app-assets/js/scripts/charts/chartjs/line/line.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"./resources/app-assets/js/scripts/charts/chartjs/bar/bar.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"./resources/app-assets/js/scripts/charts/chartjs/pie-doughnut/pie-simple.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"./resources/app-assets/js/scripts/charts/chartjs/pie-doughnut/doughnut-simple.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<!-- END PAGE LEVEL JS-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
