/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-04-04 07:51:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1580704568807L));
    _jspx_dependants.put("jar:file:/C:/FinalPj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/finalpj/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" data-textdirection=\"ltr\" class=\"loading\">\r\n");
      out.write("  <head>\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\r\n");
      out.write("    <meta name=\"description\" content=\"Robust admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"admin template, robust admin template, dashboard template, flat admin template, responsive admin template, web app\">\r\n");
      out.write("    <meta name=\"author\" content=\"PIXINVENT\">\r\n");
      out.write("    <title>Dashboard 2 - Robust Free Bootstrap Admin Template</title>\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"./resources/app-assets/images/ico/apple-icon-60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"./resources/app-assets/images/ico/apple-icon-76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"./resources/app-assets/images/ico/apple-icon-120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"./resources/app-assets/images/ico/apple-icon-152.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"./resources/app-assets/images/ico/favicon.ico\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/png\" href=\"./resources/app-assets/images/ico/favicon-32.png\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("    <meta name=\"apple-touch-fullscreen\" content=\"yes\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"default\">\r\n");
      out.write("    <!-- BEGIN VENDOR CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/bootstrap.css\">\r\n");
      out.write("    <!-- font icons-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/fonts/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/fonts/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/vendors/css/extensions/pace.css\">\r\n");
      out.write("    <!-- END VENDOR CSS-->\r\n");
      out.write("    <!-- BEGIN ROBUST CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/bootstrap-extended.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/app.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/colors.css\">\r\n");
      out.write("    <!-- END ROBUST CSS-->\r\n");
      out.write("    <!-- BEGIN Page Level CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/core/menu/menu-types/vertical-menu.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/core/menu/menu-types/vertical-overlay-menu.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/core/colors/palette-gradient.css\">\r\n");
      out.write("    <!-- END Page Level CSS-->\r\n");
      out.write("    <!-- BEGIN Custom CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/assets/css/style.css\">\r\n");
      out.write("    <!-- END Custom CSS-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body data-open=\"click\" data-menu=\"vertical-menu\" data-col=\"2-columns\" class=\"vertical-layout vertical-menu 2-columns  fixed-navbar\">\r\n");
      out.write("\r\n");
      out.write("    <!-- navbar-fixed-top-->\r\n");
      out.write("    <nav class=\"header-navbar navbar navbar-with-menu navbar-fixed-top navbar-semi-dark navbar-shadow\">\r\n");
      out.write("      <div class=\"navbar-wrapper\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li class=\"nav-item mobile-menu hidden-md-up float-xs-left\"><a class=\"nav-link nav-menu-main menu-toggle hidden-xs\"><i class=\"icon-menu5 font-large-1\"></i></a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a href=\"index.html\" class=\"navbar-brand nav-link\"><img alt=\"branding logo\" src=\"./resources/app-assets/images/logo/robust-logo-light.png\" data-expand=\"./resources/app-assets/images/logo/robust-logo-light.png\" data-collapse=\"./resources/app-assets/images/logo/robust-logo-small.png\" class=\"brand-logo\"></a></li>\r\n");
      out.write("            <li class=\"nav-item hidden-md-up float-xs-right\"><a data-toggle=\"collapse\" data-target=\"#navbar-mobile\" class=\"nav-link open-navbar-container\"><i class=\"icon-ellipsis pe-2x icon-icon-rotate-right-right\"></i></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-container content container-fluid\">\r\n");
      out.write("          <div id=\"navbar-mobile\" class=\"collapse navbar-toggleable-sm\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("              <li class=\"nav-item hidden-sm-down\"><a class=\"nav-link nav-menu-main menu-toggle hidden-xs\"><i class=\"icon-menu5\">         </i></a></li>\r\n");
      out.write("              <li class=\"nav-item hidden-sm-down\"><a href=\"#\" class=\"nav-link nav-link-expand\"><i class=\"ficon icon-expand2\"></i></a></li>\r\n");
      out.write("              <li class=\"nav-item hidden-sm-down\"><a href=\"https://pixinvent.com/bootstrap-admin-template/robust/\" target=\"_blank\" class=\"btn btn-success upgrade-to-pro\">Upgrade to PRO $24</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav float-xs-right\">\r\n");
      out.write("              <li class=\"dropdown dropdown-language nav-item\"><a id=\"dropdown-flag\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" class=\"dropdown-toggle nav-link\"><i class=\"flag-icon flag-icon-gb\"></i><span class=\"selected-language\">English</span></a>\r\n");
      out.write("                <div aria-labelledby=\"dropdown-flag\" class=\"dropdown-menu\"><a href=\"#\" class=\"dropdown-item\"><i class=\"flag-icon flag-icon-gb\"></i> English</a><a href=\"#\" class=\"dropdown-item\"><i class=\"flag-icon flag-icon-fr\"></i> French</a><a href=\"#\" class=\"dropdown-item\"><i class=\"flag-icon flag-icon-cn\"></i> Chinese</a><a href=\"#\" class=\"dropdown-item\"><i class=\"flag-icon flag-icon-de\"></i> German</a></div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown dropdown-notification nav-item\"><a href=\"#\" data-toggle=\"dropdown\" class=\"nav-link nav-link-label\"><i class=\"ficon icon-bell4\"></i><span class=\"tag tag-pill tag-default tag-danger tag-default tag-up\">5</span></a>\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-media dropdown-menu-right\">\r\n");
      out.write("                  <li class=\"dropdown-menu-header\">\r\n");
      out.write("                    <h6 class=\"dropdown-header m-0\"><span class=\"grey darken-2\">Notifications</span><span class=\"notification-tag tag tag-default tag-danger float-xs-right m-0\">5 New</span></h6>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"list-group scrollable-container\"><a href=\"javascript:void(0)\" class=\"list-group-item\">\r\n");
      out.write("                      <div class=\"media\">\r\n");
      out.write("                        <div class=\"media-left valign-middle\"><i class=\"icon-cart3 icon-bg-circle bg-cyan\"></i></div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                          <h6 class=\"media-heading\">You have new order!</h6>\r\n");
      out.write("                          <p class=\"notification-text font-small-3 text-muted\">Lorem ipsum dolor sit amet, consectetuer elit.</p><small>\r\n");
      out.write("                            <time datetime=\"2015-06-11T18:29:20+08:00\" class=\"media-meta text-muted\">30 minutes ago</time></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div></a><a href=\"javascript:void(0)\" class=\"list-group-item\">\r\n");
      out.write("                      <div class=\"media\">\r\n");
      out.write("                        <div class=\"media-left valign-middle\"><i class=\"icon-monitor3 icon-bg-circle bg-red bg-darken-1\"></i></div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                          <h6 class=\"media-heading red darken-1\">99% Server load</h6>\r\n");
      out.write("                          <p class=\"notification-text font-small-3 text-muted\">Aliquam tincidunt mauris eu risus.</p><small>\r\n");
      out.write("                            <time datetime=\"2015-06-11T18:29:20+08:00\" class=\"media-meta text-muted\">Five hour ago</time></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div></a><a href=\"javascript:void(0)\" class=\"list-group-item\">\r\n");
      out.write("                      <div class=\"media\">\r\n");
      out.write("                        <div class=\"media-left valign-middle\"><i class=\"icon-server2 icon-bg-circle bg-yellow bg-darken-3\"></i></div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                          <h6 class=\"media-heading yellow darken-3\">Warning notifixation</h6>\r\n");
      out.write("                          <p class=\"notification-text font-small-3 text-muted\">Vestibulum auctor dapibus neque.</p><small>\r\n");
      out.write("                            <time datetime=\"2015-06-11T18:29:20+08:00\" class=\"media-meta text-muted\">Today</time></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div></a><a href=\"javascript:void(0)\" class=\"list-group-item\">\r\n");
      out.write("                      <div class=\"media\">\r\n");
      out.write("                        <div class=\"media-left valign-middle\"><i class=\"icon-check2 icon-bg-circle bg-green bg-accent-3\"></i></div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                          <h6 class=\"media-heading\">Complete the task</h6><small>\r\n");
      out.write("                            <time datetime=\"2015-06-11T18:29:20+08:00\" class=\"media-meta text-muted\">Last week</time></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div></a><a href=\"javascript:void(0)\" class=\"list-group-item\">\r\n");
      out.write("                      <div class=\"media\">\r\n");
      out.write("                        <div class=\"media-left valign-middle\"><i class=\"icon-bar-graph-2 icon-bg-circle bg-teal\"></i></div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                          <h6 class=\"media-heading\">Generate monthly report</h6><small>\r\n");
      out.write("                            <time datetime=\"2015-06-11T18:29:20+08:00\" class=\"media-meta text-muted\">Last month</time></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div></a></li>\r\n");
      out.write("                  <li class=\"dropdown-menu-footer\"><a href=\"javascript:void(0)\" class=\"dropdown-item text-muted text-xs-center\">Read all notifications</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown dropdown-notification nav-item\"><a href=\"#\" data-toggle=\"dropdown\" class=\"nav-link nav-link-label\"><i class=\"ficon icon-mail6\"></i><span class=\"tag tag-pill tag-default tag-info tag-default tag-up\">8</span></a>\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-media dropdown-menu-right\">\r\n");
      out.write("                  <li class=\"dropdown-menu-header\">\r\n");
      out.write("                    <h6 class=\"dropdown-header m-0\"><span class=\"grey darken-2\">Messages</span><span class=\"notification-tag tag tag-default tag-info float-xs-right m-0\">4 New</span></h6>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"list-group scrollable-container\"><a href=\"javascript:void(0)\" class=\"list-group-item\">\r\n");
      out.write("                      <div class=\"media\">\r\n");
      out.write("                        <div class=\"media-left\"><span class=\"avatar avatar-sm avatar-online rounded-circle\"><img src=\"./resources/app-assets/images/portrait/small/avatar-s-1.png\" alt=\"avatar\"><i></i></span></div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                          <h6 class=\"media-heading\">Margaret Govan</h6>\r\n");
      out.write("                          <p class=\"notification-text font-small-3 text-muted\">I like your portfolio, let's start the project.</p><small>\r\n");
      out.write("                            <time datetime=\"2015-06-11T18:29:20+08:00\" class=\"media-meta text-muted\">Today</time></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div></a><a href=\"javascript:void(0)\" class=\"list-group-item\">\r\n");
      out.write("                      <div class=\"media\">\r\n");
      out.write("                        <div class=\"media-left\"><span class=\"avatar avatar-sm avatar-busy rounded-circle\"><img src=\"./resources/app-assets/images/portrait/small/avatar-s-2.png\" alt=\"avatar\"><i></i></span></div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                          <h6 class=\"media-heading\">Bret Lezama</h6>\r\n");
      out.write("                          <p class=\"notification-text font-small-3 text-muted\">I have seen your work, there is</p><small>\r\n");
      out.write("                            <time datetime=\"2015-06-11T18:29:20+08:00\" class=\"media-meta text-muted\">Tuesday</time></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div></a><a href=\"javascript:void(0)\" class=\"list-group-item\">\r\n");
      out.write("                      <div class=\"media\">\r\n");
      out.write("                        <div class=\"media-left\"><span class=\"avatar avatar-sm avatar-online rounded-circle\"><img src=\"./resources/app-assets/images/portrait/small/avatar-s-3.png\" alt=\"avatar\"><i></i></span></div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                          <h6 class=\"media-heading\">Carie Berra</h6>\r\n");
      out.write("                          <p class=\"notification-text font-small-3 text-muted\">Can we have call in this week ?</p><small>\r\n");
      out.write("                            <time datetime=\"2015-06-11T18:29:20+08:00\" class=\"media-meta text-muted\">Friday</time></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div></a><a href=\"javascript:void(0)\" class=\"list-group-item\">\r\n");
      out.write("                      <div class=\"media\">\r\n");
      out.write("                        <div class=\"media-left\"><span class=\"avatar avatar-sm avatar-away rounded-circle\"><img src=\"./resources/app-assets/images/portrait/small/avatar-s-6.png\" alt=\"avatar\"><i></i></span></div>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                          <h6 class=\"media-heading\">Eric Alsobrook</h6>\r\n");
      out.write("                          <p class=\"notification-text font-small-3 text-muted\">We have project party this saturday night.</p><small>\r\n");
      out.write("                            <time datetime=\"2015-06-11T18:29:20+08:00\" class=\"media-meta text-muted\">last month</time></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div></a></li>\r\n");
      out.write("                  <li class=\"dropdown-menu-footer\"><a href=\"javascript:void(0)\" class=\"dropdown-item text-muted text-xs-center\">Read all messages</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown dropdown-user nav-item\"><a href=\"#\" data-toggle=\"dropdown\" class=\"dropdown-toggle nav-link dropdown-user-link\"><span class=\"avatar avatar-online\"><img src=\"./resources/app-assets/images/portrait/small/avatar-s-1.png\" alt=\"avatar\"><i></i></span><span class=\"user-name\">John Doe</span></a>\r\n");
      out.write("                <div class=\"dropdown-menu dropdown-menu-right\"><a href=\"#\" class=\"dropdown-item\"><i class=\"icon-head\"></i> Edit Profile</a><a href=\"#\" class=\"dropdown-item\"><i class=\"icon-mail6\"></i> My Inbox</a><a href=\"#\" class=\"dropdown-item\"><i class=\"icon-clipboard2\"></i> Task</a><a href=\"#\" class=\"dropdown-item\"><i class=\"icon-calendar5\"></i> Calender</a>\r\n");
      out.write("                  <div class=\"dropdown-divider\"></div><a href=\"#\" class=\"dropdown-item\"><i class=\"icon-power3\"></i> Logout</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- main menu-->\r\n");
      out.write("    <div data-scroll-to-active=\"true\" class=\"main-menu menu-fixed menu-dark menu-accordion menu-shadow\">\r\n");
      out.write("      <!-- main menu header-->\r\n");
      out.write("      <div class=\"main-menu-header\">\r\n");
      out.write("      <input type=\"text\" placeholder=\"Search\" class=\"menu-search form-control round\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- / main menu header-->\r\n");
      out.write("      <!-- main menu content-->\r\n");
      out.write("      <div class=\"main-menu-content\">\r\n");
      out.write("        <ul id=\"main-menu-navigation\" data-menu=\"menu-navigation\" class=\"navigation navigation-main\">\r\n");
      out.write("          <li class=\" nav-item\"><a href=\"index\"><i class=\"icon-home3\"></i><span data-i18n=\"nav.dash.main\" class=\"menu-title\">Dashboard</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\" nav-item\"><a href=\"table\"><i class=\"icon-table2\"></i><span data-i18n=\"nav.bootstrap_tables.table_basic\" class=\"menu-title\">User List</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\" nav-item\"><a href=\"chart\"><i class=\"icon-stats-dots\"></i><span data-i18n=\"nav.chartjs.main\" class=\"menu-title\">Chart</span></a>\r\n");
      out.write("           <ul class=\"menu-content\">\r\n");
      out.write("              <li><a href=\"hadoopChart\" data-i18n=\"nav.chartjs.chartjs_line_charts\" class=\"menu-item\">Line charts</a>\r\n");
      out.write("              </li>\r\n");
      out.write("               <li><a href=\"chart\" data-i18n=\"nav.chartjs.chartjs_line_charts\" class=\"menu-item\">Line charts</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\" nav-item\"><a href=\"map\"><i class=\"icon-map22\"></i><span data-i18n=\"nav.maps.main\" class=\"menu-title\">Maps</span></a>\r\n");
      out.write("          </li>  \r\n");
      out.write("          <li class=\" nav-item\"><a href=\"playlist\"><i class=\"icon-copy\"></i><span data-i18n=\"nav.changelog.main\" class=\"menu-title\">Advertising list</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\" nav-item\"><a href=\"signage\"><i class=\"icon-copy\"></i><span data-i18n=\"nav.changelog.main\" class=\"menu-title\">Signage</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /main menu content-->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- / main menu-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section>\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer footer-static footer-light navbar-border\">\r\n");
      out.write("      <p class=\"clearfix text-muted text-sm-center mb-0 px-2\"><span class=\"float-md-left d-xs-block d-md-inline-block\">Copyright  &copy; 2017 <a href=\"https://themeforest.net/user/pixinvent/portfolio?ref=pixinvent\" target=\"_blank\" class=\"text-bold-800 grey darken-2\">PIXINVENT </a>, All rights reserved. </span><span class=\"float-md-right d-xs-block d-md-inline-block\">Hand-crafted & Made with <i class=\"icon-heart5 pink\"></i></span></p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- BEGIN VENDOR JS-->\r\n");
      out.write("    <script src=\"./resources/app-assets/js/core/libraries/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/tether.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/js/core/libraries/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/perfect-scrollbar.jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/unison.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/blockUI.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/jquery.matchHeight-min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/extensions/pace.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/screenfull.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- BEGIN VENDOR JS-->\r\n");
      out.write("    <!-- BEGIN PAGE VENDOR JS-->\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/charts/chart.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- END PAGE VENDOR JS-->\r\n");
      out.write("    <!-- BEGIN ROBUST JS-->\r\n");
      out.write("    <script src=\"./resources/app-assets/js/core/app-menu.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/js/core/app.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- END ROBUST JS-->\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/index.jsp(208,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${center == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "main.jsp", out, false);
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${center }.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
