/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-04-04 07:15:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" data-textdirection=\"ltr\" class=\"loading\">\r\n");
      out.write("  <head>\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\r\n");
      out.write("    <meta name=\"description\" content=\"Robust admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"admin template, robust admin template, dashboard template, flat admin template, responsive admin template, web app\">\r\n");
      out.write("    <meta name=\"author\" content=\"PIXINVENT\">\r\n");
      out.write("    <title>Dashboard 2 - Robust Free Bootstrap Admin Template</title>\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"./resources/app-assets/images/ico/apple-icon-60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"./resources/app-assets/images/ico/apple-icon-76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"./resources/app-assets/images/ico/apple-icon-120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"./resources/app-assets/images/ico/apple-icon-152.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"./resources/app-assets/images/ico/favicon.ico\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/png\" href=\"./resources/app-assets/images/ico/favicon-32.png\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("    <meta name=\"apple-touch-fullscreen\" content=\"yes\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"default\">\r\n");
      out.write("    <!-- BEGIN VENDOR CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/bootstrap.css\">\r\n");
      out.write("    <!-- font icons-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/fonts/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/fonts/flag-icon-css/css/flag-icon.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/vendors/css/extensions/pace.css\">\r\n");
      out.write("    <!-- END VENDOR CSS-->\r\n");
      out.write("    <!-- BEGIN ROBUST CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/bootstrap-extended.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/app.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/colors.css\">\r\n");
      out.write("    <!-- END ROBUST CSS-->\r\n");
      out.write("    <!-- BEGIN Page Level CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/core/menu/menu-types/vertical-menu.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/core/menu/menu-types/vertical-overlay-menu.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/app-assets/css/core/colors/palette-gradient.css\">\r\n");
      out.write("    <!-- END Page Level CSS-->\r\n");
      out.write("    <!-- BEGIN Custom CSS-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/assets/css/style.css\">\r\n");
      out.write("    <!-- END Custom CSS-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body data-open=\"click\" data-menu=\"vertical-menu\" data-col=\"1-column\" class=\"vertical-layout vertical-menu 1-column  blank-page blank-page\">\r\n");
      out.write("    <!-- ////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("    <div class=\"app-content content container-fluid\">\r\n");
      out.write("      <div class=\"content-wrapper\">\r\n");
      out.write("        <div class=\"content-header row\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content-body\"><section class=\"flexbox-container\">\r\n");
      out.write("    <div class=\"col-md-4 offset-md-4 col-xs-10 offset-xs-1  box-shadow-2 p-0\">\r\n");
      out.write("        <div class=\"card border-grey border-lighten-3 m-0\">\r\n");
      out.write("            <div class=\"card-header no-border\">\r\n");
      out.write("                <div class=\"card-title text-xs-center\">\r\n");
      out.write("                    <div class=\"p-1\"><img src=\"./resources/app-assets/images/logo/testlogo.png\" alt=\"branding logo\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h6 class=\"card-subtitle line-on-side text-muted text-xs-center font-small-3 pt-2\"><span>Login with OSTB</span></h6>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body collapse in\">\r\n");
      out.write("                <div class=\"card-block\">\r\n");
      out.write("                    <form class=\"form-horizontal form-simple\" action=\"loginimpl\" novalidate method=\"POST\">\r\n");
      out.write("                        <fieldset class=\"form-group position-relative has-icon-left mb-0\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control form-control-lg input-lg\" name=\"id\" placeholder=\"Your Username\" required>\r\n");
      out.write("                            <div class=\"form-control-position\">\r\n");
      out.write("                                <i class=\"icon-head\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                        <fieldset class=\"form-group position-relative has-icon-left\">\r\n");
      out.write("                            <input type=\"password\" class=\"form-control form-control-lg input-lg\" name=\"pwd\" placeholder=\"Enter Password\" required>\r\n");
      out.write("                            <div class=\"form-control-position\">\r\n");
      out.write("                                <i class=\"icon-key3\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                        <fieldset class=\"form-group row\">\r\n");
      out.write("                            <div class=\"col-md-6 col-xs-12 text-xs-center text-md-left\">\r\n");
      out.write("                                <fieldset>\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"remember-me\" class=\"chk-remember\">\r\n");
      out.write("                                    <label for=\"remember-me\"> Remember Me</label>\r\n");
      out.write("                                </fieldset>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 col-xs-12 text-xs-center text-md-right\"><a href=\"recover-password.html\" class=\"card-link\">Forgot Password?</a></div>\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\"><i class=\"icon-unlock2\"></i> Login</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-footer\">\r\n");
      out.write("                <div class=\"\">\r\n");
      out.write("                    <p class=\"float-sm-left text-xs-center m-0\"><a href=\"recover-password.html\" class=\"card-link\">Recover password</a></p>\r\n");
      out.write("                    <p class=\"float-sm-right text-xs-center m-0\">New to Robust? <a href=\"register-simple.html\" class=\"card-link\">Sign Up</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("\r\n");
      out.write("    <!-- BEGIN VENDOR JS-->\r\n");
      out.write("    <script src=\"./resources/app-assets/js/core/libraries/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/tether.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/js/core/libraries/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/perfect-scrollbar.jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/unison.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/blockUI.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/jquery.matchHeight-min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/extensions/pace.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/vendors/js/ui/screenfull.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- BEGIN VENDOR JS-->\r\n");
      out.write("    <!-- BEGIN PAGE VENDOR JS-->\r\n");
      out.write("    <!-- END PAGE VENDOR JS-->\r\n");
      out.write("    <!-- BEGIN ROBUST JS-->\r\n");
      out.write("    <script src=\"./resources/app-assets/js/core/app-menu.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"./resources/app-assets/js/core/app.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <!-- END ROBUST JS-->\r\n");
      out.write("    <!-- BEGIN PAGE LEVEL JS-->\r\n");
      out.write("    <!-- END PAGE LEVEL JS-->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
