/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-04-04 07:16:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function Sendfcm(ip, idx)\r\n");
      out.write("{      \r\n");
      out.write("\t\tvar speed = $(\"#speed\"+idx).val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"fcm\",\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\tdataType:\"json\",\t\r\n");
      out.write("\t\t\t\tdata:{\"speed\":speed, \"ip\":ip},\r\n");
      out.write("\t         \r\n");
      out.write("\t  \t\t\tsuccess: function(result){\r\n");
      out.write("\t  \t\t\r\n");
      out.write("\t  \t \t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\tfunction display(data) {\r\n");
      out.write("\t\tvar result = '';\r\n");
      out.write("\t\t$(data).each(function(idx, item) {\t\t\t\r\n");
      out.write("\t\t\tresult += '<tr>';\r\n");
      out.write("\t\t\tresult += '<td class=\"text-truncate\">';\r\n");
      out.write("\t\t\tresult += '<input type=\"hidden\" value = \"'+item.ip+'\" id = \"'+idx+'\">';\r\n");
      out.write("\t\t\tresult += item.ip;\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '<td class=\"text-truncate\"><span class=\"tag tag-success\">Low</span></td>';\r\n");
      out.write("\t\t\tresult += '<td class=\"valign-middle\">';\r\n");
      out.write("\t\t\tresult += '<input type=\"text\" class=\"form-control\" id=\"speed'+idx+'\">';\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '<td class=\"text-truncate\">';\t\t\t\t\t\t\t\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\tresult += '<button class=\"btn bg-info bg-darken-3 mr-1 white\" onclick=\"Sendfcm('+\"'\"+ item.ip+\"'\"+','+idx+');\">Send</button>';\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '</tr>';\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#clientip').html(result);\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction getData() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'clientgetdata',\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tdisplay(data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\tconsole.log(\"fail\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tsetInterval(getData,10000);\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("        \r\n");
      out.write("    <div class=\"app-content content container-fluid\">\r\n");
      out.write("      <div class=\"content-wrapper\">\r\n");
      out.write("        <div class=\"content-header row\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content-body\"><!-- Statistics -->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <div class=\"col-xl-3 col-lg-6 col-xs-12\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                    <div class=\"p-2 text-xs-center bg-cyan bg-darken-2 media-left media-middle\">\r\n");
      out.write("                        <i class=\"icon-user1 font-large-2 white\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"p-2 bg-cyan white media-body\">\r\n");
      out.write("                        <h5>Connect Client</h5>\r\n");
      out.write("                        <div id=\"clientnum\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-xl-3 col-lg-6 col-xs-12\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                    <div class=\"p-2 text-xs-center bg-deep-orange bg-darken-2 media-left media-middle\">\r\n");
      out.write("                        <i class=\"icon-user1 font-large-2 white\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"p-2 bg-deep-orange white media-body\">\r\n");
      out.write("                        <h5>New Client</h5>\r\n");
      out.write("                        <h5 class=\"text-bold-400\"></h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-xl-3 col-lg-6 col-xs-12\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                    <div class=\"p-2 text-xs-center bg-teal bg-darken-2 media-left media-middle\">\r\n");
      out.write("                        <i class=\"icon-cart font-large-2 white\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"p-2 bg-teal white media-body\">\r\n");
      out.write("                        <h5>New Orders</h5>\r\n");
      out.write("                        <h5 class=\"text-bold-400\"></h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-xl-3 col-lg-6 col-xs-12\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"media\">\r\n");
      out.write("                    <div class=\"p-2 text-xs-center bg-pink bg-darken-2 media-left media-middle\">\r\n");
      out.write("                        <i class=\"icon-banknote font-large-2 white\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"p-2 bg-pink white media-body\">\r\n");
      out.write("                        <h5>Total Profit</h5>\r\n");
      out.write("                        <h5 class=\"text-bold-400\"></h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/ Statistics -->\r\n");
      out.write("\r\n");
      out.write("<!--/ project charts -->\r\n");
      out.write("<section id=\"google-bar-charts\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Stacked Bar Chart -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xs-12\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                    <h4 class=\"card-title\">Stacked Bar Chart</h4>\r\n");
      out.write("                    <a class=\"heading-elements-toggle\"><i class=\"icon-ellipsis font-medium-3\"></i></a>\r\n");
      out.write("                    <div class=\"heading-elements\">\r\n");
      out.write("                        <ul class=\"list-inline mb-0\">\r\n");
      out.write("                            <li><a data-action=\"collapse\"><i class=\"icon-minus4\"></i></a></li>\r\n");
      out.write("                            <li><a data-action=\"reload\"><i class=\"icon-reload\"></i></a></li>\r\n");
      out.write("                            <li><a data-action=\"expand\"><i class=\"icon-expand2\"></i></a></li>  \r\n");
      out.write("                            <li><a data-action=\"close\"><i class=\"icon-cross2\"></i></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body collapse in\">\r\n");
      out.write("                    <div class=\"card-block\">\r\n");
      out.write("                        <p class=\"card-text\">A stacked bar chart is a bar chart that places related values atop one another. If there are any negative values, they are stacked in reverse order below the chart's axis baseline. Stacked bar charts are typically used when a category naturally divides into components. For instance, consider some hypothetical book sales, divided by genre and compared across time:</p>\r\n");
      out.write("                        <div id=\"stacked-bar-chart\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<!--/ project charts -->\r\n");
      out.write("\r\n");
      out.write("<!-- projects table with monthly chart -->\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-xl-4 col-md-6 col-sm-12\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"card-block\">\r\n");
      out.write("                    <h4 class=\"card-title\">Video Embed</h4>\r\n");
      out.write("                    <h6 class=\"card-subtitle text-muted\">Support card subtitle</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"embed-responsive embed-responsive-item embed-responsive-16by9\">\r\n");
      out.write("                    <iframe class=\"img-thumbnail\" src=\"https://www.youtube.com/embed/SsE5U7ta9Lw?rel=0&amp;controls=0&amp;showinfo=0\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-block\">\r\n");
      out.write("                    <p class=\"card-text\">Candy cupcake sugar plum oat cake wafer marzipan jujubes lollipop macaroon. Cake dragÃ©e jujubes donut chocolate bar chocolate cake cupcake chocolate topping. Dessert jelly beans toffee muffin.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"card-link\">Card link</a>\r\n");
      out.write("                    <a href=\"#\" class=\"card-link\">Another link</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-xl-8 col-lg-12\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header\">\r\n");
      out.write("                <h4 class=\"card-title\">Ongoing Projects</h4>\r\n");
      out.write("                <a class=\"heading-elements-toggle\"><i class=\"icon-ellipsis font-medium-3\"></i></a>\r\n");
      out.write("                <div class=\"heading-elements\">\r\n");
      out.write("                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                        <li><a data-action=\"reload\"><i class=\"icon-reload\"></i></a></li>\r\n");
      out.write("                        <li><a data-action=\"expand\"><i class=\"icon-expand2\"></i></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"card-block\">\r\n");
      out.write("                    <p class=\"m-0\">Total ongoing projects 6<span class=\"float-xs-right\"><a href=\"#\" target=\"_blank\">Project Summary <i class=\"icon-arrow-right2\"></i></a></span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                    <table class=\"table table-hover mb-0\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>IP</th>\r\n");
      out.write("                                <th>Priority</th>\r\n");
      out.write("                                <th>SPEED</th>\r\n");
      out.write("                                <th>Send</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody id = \"clientip\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN PAGE LEVEL JS-->\r\n");
      out.write("<script src=\"https://www.google.com/jsapi\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./resources/app-assets/js/scripts/charts/google/bar/bar-stacked.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- END PAGE LEVEL JS-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
