/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-04-04 07:22:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class table_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script>\r\n");
      out.write("\tfunction display(data) {\r\n");
      out.write("\t\tvar result = '';\r\n");
      out.write("\t\t$(data).each(function(idx, item) {\r\n");
      out.write("\t\t\tresult += '<tr>';\r\n");
      out.write("\t\t\tresult += '<td>';\r\n");
      out.write("\t\t\tresult += item.userid;\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '<td>';\r\n");
      out.write("\t\t\tresult += item.userage;\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '<td>';\r\n");
      out.write("\t\t\tresult += item.usergender;\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '<td>';\r\n");
      out.write("\t\t\tresult += item.useremail;\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '<td>';\r\n");
      out.write("\t\t\tresult += item.userphone;\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '<td>';\r\n");
      out.write("\t\t\tresult += item.useragree;\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '<td>';\r\n");
      out.write("\t\t\tresult += '<div class=\"dropdown\">';\r\n");
      out.write("\t\t\tresult += '<button class=\"dropbtn\">UserInterest</button>';\r\n");
      out.write("\t\t\tresult += '<div class=\"dropdown-content\">';\r\n");
      out.write("\t\t\tresult += '<a href=\"#\">living : ' + item.living + '</a>';\r\n");
      out.write("\t\t\tresult += '<a href=\"#\">food : ' + item.food + '</a>';\r\n");
      out.write("\t\t\tresult += '<a href=\"#\">fashion : ' + item.fashion + '</a>';\r\n");
      out.write("\t\t\tresult += '<a href=\"#\">culture : ' + item.culture + '</a>';\r\n");
      out.write("\t\t\tresult += '<a href=\"#\">etc: ' + item.etc + '</a>';\r\n");
      out.write("\t\t\tresult += '</div>';\r\n");
      out.write("\t\t\tresult += '</div>';\r\n");
      out.write("\t\t\tresult += '</td>';\r\n");
      out.write("\t\t\tresult += '</tr>';\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#userid').html(result);\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction getData() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'tablegetdata',\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tdisplay(data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\talert(\"fail\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tgetData();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".dropdown {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("\tmin-width: 160px;\r\n");
      out.write("\tbox-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tpadding: 12px 16px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a:hover {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .dropbtn {\r\n");
      out.write("\tbackground-color: #3e8e41;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"app-content content container-fluid\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"content-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Table head options start -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">User List</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"heading-elements-toggle\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"icon-ellipsis font-medium-3\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"heading-elements\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list-inline mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"collapse\"><i class=\"icon-minus4\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"reload\"><i class=\"icon-reload\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"expand\"><i class=\"icon-expand2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a data-action=\"close\"><i class=\"icon-cross2\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body collapse in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead class=\"thead-inverse\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>AGE</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>GENDER</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>EMAIL</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>PHONE</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>AGREE</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>INTREST</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody id=\"userid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Table head options end -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
